import type { Metadata } from "next"
import { Geist, Geist_Mono, Tajawal } from "next/font/google"
import "./globals.css"
import { Header } from "@/components/organisms/header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const Tajawalfont = Tajawal({
  variable: "--font-tajwal",
  weight: ["200", "300", "400", "500", "700", "800", "900"]
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Karzoun app",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Tajawalfont.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
